% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d9_34('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d9_34(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=34.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d9_34(V,L,D,R,LINEAGE), P=34.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d9_34(V,L,D,R,LINEAGE), P=34.
