% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d6_23('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d6_23(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=23.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d6_23(V,L,D,R,LINEAGE), P=23.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d6_23(V,L,D,R,LINEAGE), P=23.
