% schema:
source bt('V':int, 'L':int, 'D':int, 'R':int, 'd1_2':string, 'LINEAGE':string).
view d1_2('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d1_2(V,L,D,R,LINEAGE) :- bt(V,L,D,R,S1,LINEAGE), S1='true'.

% rules for update strategy:
-bt(V,L,D,R,S1,LINEAGE) :- bt(V,L,D,R,S1,LINEAGE), NOT d1_2(V,L,D,R,LINEAGE), S1='true'.
+bt(V,L,D,R,S1,LINEAGE) :- NOT bt(V,L,D,R,S1,LINEAGE), d1_2(V,L,D,R,LINEAGE), S1='true'.