% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d6_22('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d6_22(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=22.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d6_22(V,L,D,R,LINEAGE), P=22.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d6_22(V,L,D,R,LINEAGE), P=22.
