version: '3.8'
services:
  db:
    image: postgres:11.2
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./setup_files:/home
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    tty:
      true
volumes:
  postgresql:
    driver: local