# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\x1b\n\x07Request\x12\x10\n\x08json_str\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08json_str\x18\x02 \x01(\t22\n\x0e\x46RSPropagation\x12 \n\x07on_post\x12\x08.Request\x1a\t.Response\"\x00\x32\x32\n\x0e\x46RSTermination\x12 \n\x07on_post\x12\x08.Request\x1a\t.Response\"\x00\x32(\n\x04Lock\x12 \n\x07on_post\x12\x08.Request\x1a\t.Response\"\x00\x32*\n\x06Unlock\x12 \n\x07on_post\x12\x08.Request\x1a\t.Response\"\x00\x32\x32\n\x0eTPLPropagation\x12 \n\x07on_post\x12\x08.Request\x1a\t.Response\"\x00\x32\x32\n\x0eTPLTermination\x12 \n\x07on_post\x12\x08.Request\x1a\t.Response\"\x00\x32+\n\x08YCSBLoad\x12\x1f\n\x06on_get\x12\x08.Request\x1a\t.Response\"\x00\x32\'\n\x04YCSB\x12\x1f\n\x06on_get\x12\x08.Request\x1a\t.Response\"\x00\x32\x30\n\rTPCCLoadLocal\x12\x1f\n\x06on_get\x12\x08.Request\x1a\t.Response\"\x00\x32\x33\n\x10TPCCLoadCustomer\x12\x1f\n\x06on_get\x12\x08.Request\x1a\t.Response\"\x00\x32\'\n\x04TPCC\x12\x1f\n\x06on_get\x12\x08.Request\x1a\t.Response\"\x00\x32,\n\tValChange\x12\x1f\n\x06on_get\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=14
  _REQUEST._serialized_end=41
  _RESPONSE._serialized_start=43
  _RESPONSE._serialized_end=71
  _FRSPROPAGATION._serialized_start=73
  _FRSPROPAGATION._serialized_end=123
  _FRSTERMINATION._serialized_start=125
  _FRSTERMINATION._serialized_end=175
  _LOCK._serialized_start=177
  _LOCK._serialized_end=217
  _UNLOCK._serialized_start=219
  _UNLOCK._serialized_end=261
  _TPLPROPAGATION._serialized_start=263
  _TPLPROPAGATION._serialized_end=313
  _TPLTERMINATION._serialized_start=315
  _TPLTERMINATION._serialized_end=365
  _YCSBLOAD._serialized_start=367
  _YCSBLOAD._serialized_end=410
  _YCSB._serialized_start=412
  _YCSB._serialized_end=451
  _TPCCLOADLOCAL._serialized_start=453
  _TPCCLOADLOCAL._serialized_end=501
  _TPCCLOADCUSTOMER._serialized_start=503
  _TPCCLOADCUSTOMER._serialized_end=554
  _TPCC._serialized_start=556
  _TPCC._serialized_end=595
  _VALCHANGE._serialized_start=597
  _VALCHANGE._serialized_end=641
# @@protoc_insertion_point(module_scope)
