% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d10_28('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d10_28(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=28.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d10_28(V,L,D,R,LINEAGE), P=28.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d10_28(V,L,D,R,LINEAGE), P=28.
