networks:
  dejima_net:
    driver: bridge
    ipam:
      driver: default
services:
  alliance1-db:
    cap_add:
    - NET_ADMIN
    container_name: alliance1-db
    environment:
    - PEER_NAME=alliance1
    image: ekayim/dejima-pg
    networks:
      dejima_net: null
    volumes:
    - ./db/postgresql.conf:/etc/postgresql.conf
    - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
    - ./db/setup_files:/etc/setup_files
  alliance1-proxy:
    cap_add:
    - NET_ADMIN
    command: gunicorn -b 0.0.0.0:8000 --threads 11 server:app
    container_name: alliance1-proxy
    depends_on:
    - alliance1-db
    environment:
    - PEER_NAME=alliance1
    image: ekayim/dejima-proxy:latest
    networks:
      dejima_net: null
    ports:
    - 8001:8000
    volumes:
    - ./proxy:/code
  provider1-db:
    cap_add:
    - NET_ADMIN
    container_name: provider1-db
    environment:
    - PEER_NAME=provider1
    image: ekayim/dejima-pg
    networks:
      dejima_net: null
    volumes:
    - ./db/postgresql.conf:/etc/postgresql.conf
    - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
    - ./db/setup_files:/etc/setup_files
  provider1-proxy:
    cap_add:
    - NET_ADMIN
    command: gunicorn -b 0.0.0.0:8000 --threads 11 server:app
    container_name: provider1-proxy
    depends_on:
    - provider1-db
    environment:
    - PEER_NAME=provider1
    image: ekayim/dejima-proxy:latest
    networks:
      dejima_net: null
    ports:
    - 8002:8000
    volumes:
    - ./proxy:/code
version: '3'
