% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d2_3('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d2_3(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=3.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d2_3(V,L,D,R,LINEAGE), P=3.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d2_3(V,L,D,R,LINEAGE), P=3.
