% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d2_33('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d2_33(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=33.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d2_33(V,L,D,R,LINEAGE), P=33.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d2_33(V,L,D,R,LINEAGE), P=33.
