% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'A':int, 'LINEAGE':string).
view d0_1('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d0_1(V,L,D,R,LINEAGE) :- mt(V,L,D,R,A,LINEAGE), A=1.

% rules for update strategy:
-mt(V,L,D,R,A,LINEAGE) :- mt(V,L,D,R,A,LINEAGE), NOT d0_1(V,L,D,R,LINEAGE), A=1.
+mt(V,L,D,R,A,LINEAGE) :- NOT mt(V,L,D,R,A,LINEAGE), d0_1(V,L,D,R,LINEAGE), A=1.
