% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d7_37('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d7_37(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=37.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d7_37(V,L,D,R,LINEAGE), P=37.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d7_37(V,L,D,R,LINEAGE), P=37.
