% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d8_13('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d8_13(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=13.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d8_13(V,L,D,R,LINEAGE), P=13.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d8_13(V,L,D,R,LINEAGE), P=13.
