% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d3_42('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d3_42(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=42.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d3_42(V,L,D,R,LINEAGE), P=42.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d3_42(V,L,D,R,LINEAGE), P=42.
