% schema:
source mt('V':int, 'L':int, 'D':int, 'R':int, 'P':int, 'LINEAGE':string).
view d5_24('V':int, 'L':int, 'D':int, 'R':int, 'LINEAGE':string).

% view definition
d5_24(V,L,D,R,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), P=24.

% rules for update strategy:
-mt(V,L,D,R,P,LINEAGE) :- mt(V,L,D,R,P,LINEAGE), NOT d5_24(V,L,D,R,LINEAGE), P=24.
+mt(V,L,D,R,P,LINEAGE) :- NOT mt(V,L,D,R,P,LINEAGE), d5_24(V,L,D,R,LINEAGE), P=24.
